apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: test1
spec:
  replicas: 12
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "1d"]